### ISSUE TITLE
Input params such as fund, registrant by url

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/competitions#11] opened 2018-01-11 13:18 UTC
https://github.com/melonproject/competitions/blob/master/src/Competition.sol#L15-L16

similar to https://github.com/melonproject/faucet

**Comment by GauthamN** [comment] 2018-01-31 12:59
Duplicate of https://github.com/melonproject/competitions/issues/10

**Closed** 2018-01-31 13:01 UTC
